### ISSUE TITLE
“generatedColumn” was wrong when the name first appeared and the name mangled

### ISSUE THREAD

**Issue by markfan** [mozilla/source-map#223] opened 2016-02-02 15:46 UTC
source code 
![qq 20160202232457](https://cloud.githubusercontent.com/assets/2517143/12754136/0fc53b5c-ca05-11e5-8009-8cb837330940.png)

generated code 
![qq 20160202234732](https://cloud.githubusercontent.com/assets/2517143/12754851/e484711c-ca07-11e5-8344-d133a3b839cf.png)

debug code & info
![qq 20160202232648](https://cloud.githubusercontent.com/assets/2517143/12754196/4675daee-ca05-11e5-84c7-5182736ea1c9.png)
![qq 20160202232558](https://cloud.githubusercontent.com/assets/2517143/12754202/4b859204-ca05-11e5-8157-e2307630c056.png)

we can see the position in source code(line: 17,col: 13) and the position in gennerated code(line:0,  col:192 ), but the generatedColumn in mapping is 191. 

ps: the editor display line & colnum beginning with 1 and the code first line is comment

**Comment by tromey** [comment] 2017-09-22 16:40
I think some kind of reproducer would be helpful here.  I guess this is a bug in the producer?  The very best thing would be a new test case.

**Comment by jkrems** [comment] 2021-04-18 02:01
Closing since we lack a full test case for this.

**Closed by jkrems** 2021-04-18 02:01 UTC
