### ISSUE TITLE
Broken in Node.js v18.

### ISSUE THREAD

**Issue by Qard** [mozilla/source-map#454] opened 2022-04-23 00:52 UTC
Apparently this module environment detects the browser by looking for the "fetch" function but fetch is now available in Node.js v18. It no longer works in Node.js because it thinks it's a browser. 😐

**Comment by maxmilton** [comment] 2022-04-24 03:16
Reading through https://github.com/terser/terser/pull/1164 it seems this was already fixed years ago back in 2018 but never released. Looks like issue https://github.com/mozilla/source-map/issues/452 is about publishing a new release.

**Comment by jacobq** [comment] 2022-05-17 21:11
Duplicate of #432 / #452

**Comment by eemeli** [comment] 2022-06-06 16:23
This is fixed in [`source-map@0.7.4`](https://www.npmjs.com/package/source-map/v/0.7.4).

**Closed by eemeli** 2022-06-06 16:23 UTC
