### ISSUE TITLE
Is this repo really open source ?

### ISSUE THREAD

**Issue by guimard** [mozilla/source-map#451] opened 2022-02-12 08:00 UTC
Hi,

it impossible to reproduce lib/mappings.wasm build. The result given by https://github.com/fitzgen/source-map-mappings is different and doesn't work.

Why do you provide closed-source file ? Is there something hidden ?

**Comment by asdofindia** [comment] 2022-05-28 18:55
There is a difference between a binary being not reproducible and a binary being proprietary.

It seems to me like lib/mappings.wasm can be reproduced only with the original versions of the toolchain on the original computer 4 years ago. That doesn't make it proprietary.

**Comment by kapouer** [comment] 2022-05-30 17:43
Hi, like the reporter of this issue, I tried to compile source-map-mappings to get it running along with source-map.
However some source-map-mappings methods expected by source-map have not the correct names.
If there is an incompatibility between versions, it is more likely to be between source-map-mappings and source-map,
than caused by toolchain versions.

**Comment by guimard** [comment] 2022-06-12 02:40
> There is a difference between a binary being not reproducible and a binary being proprietary.
> 
> It seems to me like lib/mappings.wasm can be reproduced only with the original versions of the toolchain on the original computer 4 years ago. That doesn't make it proprietary.

_"Original versions of the toolchain, original computer"_ and original own changes !

1. This doesn't make it opensource
2. The current compilation result is so different that there is no suggestion that the published file has any relation to the source file allegedly used

**Comment by ochameau** [comment] 2022-10-19 18:50
The wasm file was built in 2018 and many things changed (rust, cargo, wasm libraries and tools).
I tried very hard to try to rebuild using version from that old year, but I never managed to get the exact same binary file.
I agree with previous comment, the binary was built from sources on the other repo and nothing is hidden.

Having said that we ought to do a refresh on the wasm binary, using latest version of everything.

I'll be doing that in #465.

**Comment by ochameau** [comment] 2022-11-08 17:28
#465 landed.
WASM sources are now in the repo [over here](https://github.com/mozilla/source-map/tree/master/wasm-mappings/src).
And the WASM binary has been refreshed [over there](https://github.com/mozilla/source-map/blob/master/lib/mappings.wasm).
This binary should be easily reproducible.
I mentioned the precise versions of all the environment [in the commit message](https://github.com/mozilla/source-map/pull/465/commits/b56a5c7278cf8ae9537fae2933c2c4fb57d7cd2e).

**Closed by ochameau** 2022-11-08 17:28 UTC
