### ISSUE TITLE
Environment detection broken in Node 18

### ISSUE THREAD

**Issue by lukastaegert** [mozilla/source-map#460] opened 2022-09-23 07:53 UTC
This package uses

```js
if (typeof fetch === "function") {
  // ...
}
```

to detect if it is running in a browser environment. This no longer works in latest Node as `fetch` is now available as a regular Node global. I currently use `delete global.fetch` in my code to work around this, but it would be preferable if it uses a better environment sniffing algorithm, e.g. by checking for for Node-only globals.

**Comment by eemeli** [comment] 2022-09-23 12:02
Duplicate of #349.

**Closed by eemeli** 2022-09-23 12:02 UTC
