### ISSUE TITLE
Build issue for reactjs application

### ISSUE THREAD

**Issue by Krunalvaghasiya** [mozilla/source-map#403] opened 2019-07-31 12:24 UTC
When build reactjs app, there are failed build error:

`throw new Error('"' + relativeSource + '" is not in the SourceMap.');`

**Comment by solenoo** [comment] 2019-07-31 12:34
I can confirm receiving the same error as well 
` throw new Error('"' + relativeSource + '" is not in the SourceMap.');

Error: "." is not in the SourceMap.`

**Comment by niharikanarain** [comment] 2019-07-31 12:46
Same here if it helps to know frequency of occurrences:

throw new Error('"' + relativeSource + '" is not in the SourceMap.');

**Comment by SevenLines** [comment] 2019-07-31 13:30
got the same bug on Vue project

**Comment by bdombro** [comment] 2019-07-31 16:11
I have this issue too, and I found that it doesn't occur with a minimal react app. I monkey patched the file using patch-package for now.

```
// patch-package to fix build error. Ref: https://github.com/mozilla/source-map/issues/403
if (nullOnMissing || relativeSource == ".") {
```

**Comment by loganfsmyth** [comment] 2019-07-31 16:24
This module has not had any recent changes, so if you are seeing new errors, it is most likely due to changes in another package.

What is the stacktrace of this error?

**Comment by romamd** [comment] 2019-08-01 07:09
Fixed in https://github.com/webpack/webpack-sources/releases/tag/v1.4.1, running `npm install` solves the issue

**Closed** 2019-08-01 15:06 UTC
