### ISSUE TITLE
Invalid line numbers since 0.1.33

### ISSUE THREAD

**Issue by Toilal** [mozilla/source-map#132] opened 2014-09-03 09:12 UTC
I use grunt-contrib-concat and have an issue with debugging through sourcemaps using firefox and intellij IDEA. It works properly with Chrome though.

I have made some tests with grunt-contrib-concat using `npm shrinkwrap` to force source-map dependency version. 

It works with grunt-contrib-concat, using source-map 0.1.32. Then, with any later source-map release, sourcemap are recognized, but a bit buggy with some tools. They works with chrome, but not with firefox nor intellij idea. Lines mapping seems to have an additionnal offset and setting breakpoints on sources will break at invalid lines, 1 or 2 lines after set breakpoint ...

**Comment by jkrems** [comment] 2021-04-18 01:27
Closing since there have been a couple of versions since this was reported. If this happens again, we should document a clear test case with expected behavior.

**Closed by jkrems** 2021-04-18 01:27 UTC
