### ISSUE TITLE
Error: Invalid mapping from compass-sass-mixins/lib/compass/utilities/general/_clearfix.sass

### ISSUE THREAD

**Issue by aanno** [mozilla/source-map#255] opened 2017-02-24 13:11 UTC
I'm using the compass-sass-mixins 0.12.7 from a webpack 2.2.1 build. When I enable source maps, the following error occurs:

```
[at-loader] Using typescript@2.2.1 from typescript and "tsconfig.json" from /home/tpasch/scm/wroomer/nextcar/tsconfig.json.


/home/tpasch/scm/wroomer/nextcar/node_modules/source-map/lib/source-map-generator.js:277
      throw new Error('Invalid mapping: ' + JSON.stringify({
            ^
Error: Invalid mapping: {"generated":{"line":1,"column":19257},"source":"webpack:///node_modules/compass-sass-mixins/lib/compass/utilities/general/_clearfix.sass","original":{"line":35,"column":-1},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (/home/tpasch/scm/wroomer/nextcar/node_modules/source-map/lib/source-map-generator.js:277:13)
    at SourceMapGenerator_addMapping [as addMapping] (/home/tpasch/scm/wroomer/nextcar/node_modules/source-map/lib/source-map-generator.js:101:12)
    at /home/tpasch/scm/wroomer/nextcar/node_modules/source-map/lib/source-node.js:345:13
    at SourceNode_walk [as walk] (/home/tpasch/scm/wroomer/nextcar/node_modules/source-map/lib/source-node.js:224:9)
    at SourceNode_walk [as walk] (/home/tpasch/scm/wroomer/nextcar/node_modules/source-map/lib/source-node.js:220:13)
    at SourceNode_walk [as walk] (/home/tpasch/scm/wroomer/nextcar/node_modules/source-map/lib/source-node.js:220:13)
    at SourceNode_toStringWithSourceMap [as toStringWithSourceMap] (/home/tpasch/scm/wroomer/nextcar/node_modules/source-map/lib/source-node.js:336:8)
    at ConcatSource.proto.sourceAndMap (/home/tpasch/scm/wroomer/nextcar/node_modules/webpack-sources/lib/SourceAndMapMixin.js:28:32)
    at Compilation.<anonymous> (/home/tpasch/scm/wroomer/nextcar/node_modules/webpack/lib/SourceMapDevToolPlugin.js:57:32)
    at Array.map (native)
    at Compilation.<anonymous> (/home/tpasch/scm/wroomer/nextcar/node_modules/webpack/lib/SourceMapDevToolPlugin.js:43:84)
    at Array.forEach (native)
    at Compilation.<anonymous> (/home/tpasch/scm/wroomer/nextcar/node_modules/webpack/lib/SourceMapDevToolPlugin.js:42:11)
    at Compilation.applyPlugins1 (/home/tpasch/scm/wroomer/nextcar/node_modules/tapable/lib/Tapable.js:75:14)
    at self.applyPluginsAsync.err (/home/tpasch/scm/wroomer/nextcar/node_modules/webpack/lib/Compilation.js:630:11)
    at next (/home/tpasch/scm/wroomer/nextcar/node_modules/tapable/lib/Tapable.js:138:11)
```

My version of node_modules/compass-sass-mixins/lib/compass/utilities/general/_clearfix.sass has the following content:

```
// @doc off
// Extends the bottom of the element to enclose any floats it contains.
// @doc on

@import hacks

// This basic method is preferred for the usual case, when positioned
// content will not show outside the bounds of the container.
//
// Recommendations include using this in conjunction with a width.
// Credit: [quirksmode.org](http://www.quirksmode.org/blog/archives/2005/03/clearing_floats.html)
=clearfix
  overflow: hidden
  +has-layout

// This older method from Position Is Everything called
// [Easy Clearing](http://www.positioniseverything.net/easyclearing.html)
// has the advantage of allowing positioned elements to hang
// outside the bounds of the container at the expense of more tricky CSS.
=legacy-pie-clearfix
  &:after
    content: "\0020"
    display: block
    height: 0
    clear: both
    overflow: hidden
    visibility: hidden
  +has-layout

// This is an updated version of the PIE clearfix method that reduces the amount of CSS output.
// If you need to support Firefox before 3.5 you need to use `legacy-pie-clearfix` instead.
//
// Adapted from: [A new micro clearfix hack](http://nicolasgallagher.com/micro-clearfix-hack/)
=pie-clearfix
  &:after
    content: ""
    display: table
    clear: both
  +has-layout
```
My version of source-map is 0.5.6.

**Comment by Slapbox** [comment] 2017-09-03 17:57
Same issue.

**Comment by tromey** [comment] 2017-09-22 17:27
Duplicate of #254

**Closed by tromey** 2017-09-22 17:27 UTC
