### ISSUE TITLE
Not using sourcesContent when it's available

### ISSUE THREAD

**Issue by glen-84** [mozilla/source-map#211] opened 2015-09-24 13:58 UTC
Both Firefox 41.0 and Firefox Developer Edition 42.0a2 try to load `http://localhost:3000/node_modules/bootstrap/scss/_normalize.scss`, instead of reading the data from `sourcesContent`.
![sm-issue](https://cloud.githubusercontent.com/assets/261509/10075169/99bd1142-62d4-11e5-9280-40318835a96d.png)

This works fine with Chrome 45.0.2454.99.

**Comment by fitzgen** [comment] 2015-09-24 14:57
Can you share your test case and describe the exact steps to reproduce, please?

**Comment by glen-84** [comment] 2015-09-24 17:59
https://github.com/glen-84/ff-sourcemaps-issue

You'll need Node.js.

```
$ npm install
$ gulp
````

If you look [here](https://github.com/glen-84/ff-sourcemaps-issue/blob/master/gulpfile.babel.js#L6), there are two options, one where the source file is accessible, and one where it isn't. In both cases I see the "Style sheet could not be loaded" error, and with option 2 it doesn't load the source at all.

The `sourcesContent` is available in both cases, and should be used (and is used in Chrome).

Am I doing something wrong?

(ultimately I want the source files in the src folder [which is not web-accessible], but I tried something similar to option 2 when I had other issues with gulp-sourcemaps)

**Comment by Oikio** [comment] 2015-11-02 11:51
Hello,
I had similar issue, in my case it looks like Firefox takes separate map file when sass compiles with this options (I use grunt):
```
    options: {
      sourceMap: true,
      sourceMapEmbed: true,
      sourceMapContents: true
    }
```
Setting sourceMap to false solved it for me. Embedded source maps with content are in .css files and everything works fine.

**Comment by Fuxy22** [comment] 2016-05-11 16:24
I have run into this issue as well. Chrome links to the source file without requiring access to  the actual file but Firefox requires access.

I'm running Firefox 46.

If this could not be fixed at least I wish there was a way of adding the project folder and mapping it like in chrome.

**Comment by szachara** [comment] 2017-04-25 14:59
The same problem here, i'm attaching sourcemap file, how we could solve this problem?

![2017-04-25 1](https://cloud.githubusercontent.com/assets/86900/25392245/71c58e68-29d8-11e7-9345-1bf2f1be33d0.png)

[lib.css.zip](https://github.com/mozilla/source-map/files/955488/lib.css.zip)

**Comment by tromey** [comment] 2017-09-22 16:35
Thank you for the report.

I agree this is a bug, but I don't believe it is a bug in the source-map library.  Instead I think it is a bug in the Firefox style editor (actually in the stylesheets actor).

I've filed a bug upstream, which you can follow if you want to see when it is fixed.  https://bugzilla.mozilla.org/show_bug.cgi?id=1402382

I am closing this.

**Closed by tromey** 2017-09-22 16:35 UTC
