### ISSUE TITLE
Unable to resolve source-map issue in closure-loader

### ISSUE THREAD

**Issue by vmonisha69** [mozilla/source-map#380] opened 2019-03-07 13:01 UTC
ERROR in ./content/closure-polyfill.js
Module build failed: TypeError: aSourceMapConsumer.eachMapping is not a function

**Comment by loganfsmyth** [comment] 2019-03-07 16:29
It is hard to say without a stacktrace. Perhaps the wrong version of `source-map` is being loaded?

**Comment by jkrems** [comment] 2021-04-18 02:44
Closing since we're lacking a clear reproduction / test case for this error.

**Closed by jkrems** 2021-04-18 02:44 UTC
